Description: >
  Ybrahin Martinez - Udagram Project

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
  
  NameBucket:
    Description: Unique name of the S3 bucket where stores the files to deploy
    Type: String
    Default: s3-bucket

Resources:

  UagramBucketS3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref NameBucket
    DeletionPolicy: Delete

Outputs: 
  DataBucket:
    Value: !Ref UagramBucketS3
    Description: Udagram bucket that stores web archive
    Export:
      Name: !Sub ${EnvironmentName}-DataBucket

  DataBucketARN:
    Value: !Join ["", ["arn:aws:s3:::", !Ref "UagramBucketS3", "/*"]]
    Export:
      Name: !Sub ${EnvironmentName}-DataBucketARN
